apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ include "flt-gw.fullname" . }}-configmap
data: 
{{- if not .Values.tlsSecretEnable  }}
  {{- range .Values.configMap.files }}
    {{- .name | nindent 2 }}: |
    {{- .data | nindent 4 }}
  {{- end }}
{{- end }}
  {{- range .Values.configMap.list -}}
  {{- .key | nindent 2 }}: {{ .value | quote }}
  {{- end}}
