apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flt-gw.fullname" . }}
  labels:
    {{- include "flt-gw.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "flt-gw.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "flt-gw.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "flt-gw.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-map-volume
              mountPath: {{ .Values.configMap.path }}
              readOnly: true
          envFrom:
            - secretRef:
                name: {{ include "flt-gw.name" . }}-env-secrets  
{{- if .Values.tlsSecretEnable }}
          env: 
            - name: TLS_CERT
              valueFrom: 
                secretKeyRef:
                  name: {{ .Values.tlsSecretName }}
                  key: tls.crt
                  optional: false 
            - name: TLS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.tlsSecretName }}
                  key: tls.key
                  optional: false
{{- else }}
          env: 
            - name: TLS_CERT
              valueFrom: 
                configMapKeyRef:
                  name: {{ include "flt-gw.fullname" . }}-configmap
                  key: TLS_CERT
                  optional: false 
            - name: TLS_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "flt-gw.fullname" . }}-configmap
                  key: TLS_KEY
                  optional: false
{{- end }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-map-volume
          configMap:
            name: {{ include "flt-gw.name" . }}-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
