apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flt-gw.name" . }}-env-secrets
  labels:
    {{- include "flt-gw.labels" . | nindent 4 }}
data:
  {{- range .Values.envSecrets }}
  {{- .key | nindent 4 }}: {{ .value | b64enc }}
  {{- end }} 