apiVersion: v1
kind: Service
metadata:
  name: {{ include "flt-gw.fullname" . }}
  labels:
    {{- include "flt-gw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
  selector:
    {{- include "flt-gw.selectorLabels" . | nindent 4 }}
