apiVersion: v1
kind: Service
metadata:
  name: {{ include "flt-gw.fullname" . }}
  labels:
    {{- include "flt-gw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    {{- include "flt-gw.selectorLabels" . | nindent 4 }}
